# Generated by Django 5.1.7 on 2025-03-30 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the entity.', primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Title of the entity.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the entity.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the entity was created.')),
                ('user', models.ForeignKey(default=None, help_text='The service user that owns this entity.', on_delete=django.db.models.deletion.CASCADE, related_name='entities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
