apiVersion: v1
kind: Secret
metadata:
  name: review-secrets

type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_DATABASE: reviewdb
  MYSQL_USER: reviewuser
  MYSQL_PASSWORD: reviewpass
  MYSQL_HOST: mariadb

  AUTH0_DOMAIN: domain.eu.auth0.com
  AUTH0_API_AUDIENCE: https://domain.eu.auth0.com/api/v2/
  SECRET_KEY: secret
  DJANGO_ALLOWED_HOSTS: app-domain.com
  DEBUG: "false"
  DEFAULT_ADMIN_USERNAME: admin
  DEFAULT_ADMIN_EMAIL: admin@example.com
  DEFAULT_ADMIN_PASSWORD: adminpassword
  DEFAULT_SERVICE_USERNAME: service_account
