# Generated by Django 5.1.7 on 2025-03-30 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the review.', primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Title of the review.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed review description.')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='Rating from 1 (worst) to 5 (best).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the review was created.')),
                ('entity', models.ForeignKey(help_text='The entity associated with this review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='entity.entity')),
                ('user', models.ForeignKey(help_text='The user who wrote the review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
