name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy env-sample
        run: cp env-sample .env


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & start review-it service
        run: |
          docker compose up --build -d review-it

      - name: Run migrations & tests (using SQLite)
        run: |
          docker compose exec -T review-it sh -c "\
            python manage.py migrate --noinput && \
            python manage.py test \
          "

      - name: Tear down
        if: always()
        run: |
          docker compose down --volumes --remove-orphans
