name: Django CI

on:
  push:       { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy env-sample
        run: cp env-sample .env

      - name: Load env variables into shell
        run: |
          set -o allexport
          source .env
          set +o allexport

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & start services
        run: |
          docker compose up --build -d

          # Wait for mariadb to become healthy
          until docker compose exec -T mariadb mysqladmin ping -h localhost --silent; do
            echo "Waiting for database…"
            sleep 5
          done

      - name: Create & grant test DB
        run: |
          docker compose exec -T mariadb mysql \
            --user=root \
            --password="${MYSQL_ROOT_PASSWORD}" \
            --host=localhost \
            --port=3306 \
            -e "CREATE DATABASE IF NOT EXISTS \`${MYSQL_DATABASE}_test\`; \
                GRANT ALL PRIVILEGES ON \`${MYSQL_DATABASE}_test\`.* \
                  TO '${MYSQL_USER}'@'%'; \
                FLUSH PRIVILEGES;"

      - name: Run migrations & tests
        run: |
          docker compose exec -T review-it sh -c "\
            python manage.py migrate --noinput && \
            python manage.py test \
          "

      - name: Tear down
        if: always()
        run: |
          docker compose down --volumes --remove-orphans
