name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy env-sample
        run: cp env-sample .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & run services
        run: |
          docker compose up --build -d
          # Wait for mariadb to become healthy
          until docker compose exec -T mariadb mysqladmin ping -h localhost --silent; do
            echo "Waiting for database…"
            sleep 5
          done

      - name: Create and grant test database privileges
        run: |
          # Use the root account to create & grant privileges on the test DB
          docker compose exec -T mariadb mysql \
            -u root \
            -p"${MYSQL_ROOT_PASSWORD}" \
            -e "\
              CREATE DATABASE IF NOT EXISTS \`${MYSQL_DATABASE}_test\`; \
              GRANT ALL PRIVILEGES ON \`${MYSQL_DATABASE}_test\`.* TO '${MYSQL_USER}'@'%'; \
              FLUSH PRIVILEGES;\
            "

      - name: Run migrations & tests
        run: |
          docker compose exec -T review-it sh -c "\
            python manage.py migrate --noinput && \
            python manage.py test \
          "

      - name: Tear down
        if: always()
        run: |
          docker compose down --volumes --remove-orphans
