name: Django CI

on:
  push:       { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy env-sample
        run: cp env-sample .env

      - name: Load .env vars into GitHub Actions environment
        shell: bash
        run: |
          while IFS='=' read -r key value; do
            # skip comments and empty lines
            [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
            echo "$key=$value" >> "$GITHUB_ENV"
          done < .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & start services
        run: |
          docker compose up --build -d

          # Wait for mariadb to become healthy
          until docker compose exec -T mariadb mysqladmin ping -h localhost --silent; do
            echo "Waiting for database…"
            sleep 5
          done

      - name: Grant create-db rights
        run: |
          docker compose exec -T mariadb mysql \
            --user=root \
            --password="${{ env.MYSQL_ROOT_PASSWORD }}" \
            -e "GRANT CREATE, DROP ON *.* TO '${{ env.MYSQL_USER }}'@'%'; FLUSH PRIVILEGES;"

      - name: Run migrations & tests
        run: |
          docker compose exec -T review-it sh -c "\
            python manage.py migrate --noinput && \
            python manage.py test \
          "

      - name: Tear down
        if: always()
        run: |
          docker compose down --volumes --remove-orphans
